# Generated by Django 4.1.3 on 2022-11-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('liked', models.BooleanField(default=False)),
                ('image', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
