# Generated by Django 4.1.3 on 2022-11-06 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mug', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mug',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('payed', models.BooleanField(default=False)),
                ('mug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mug.mug')),
            ],
        ),
    ]
